<?php

class ConfigKeys {

    const CAPTCHA_CONTACT_ENABLED = 'CAPTCHA_CONTACT_ENABLED';
    const CAPTCHA_REGISTER_ENABLED = 'CAPTCHA_REGISTER_ENABLED';
    const CAPTCHA_PRIVATE_KEY = 'CAPTCHA_PRIVATE_KEY';
    const CAPTCHA_SITE_KEY = 'CAPTCHA_SITE_KEY';
    
}